//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Perfect.Sale.Core.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS2005;Initial Catalog=ERP.Sale.2.9.1;User ID=sa")]
        public string ERP_THANHTAMConnectionString {
            get {
                return ((string)(this["ERP_THANHTAMConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS2005;Initial Catalog=ERP.Sale.2.9.1;Integrated Security=T" +
            "rue")]
        public string ERP_THANHTAMConnectionString1 {
            get {
                return ((string)(this["ERP_THANHTAMConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=PC10010100\\SQLEXPRESS;Initial Catalog=VanHoaDienAnh;Integrated Securi" +
            "ty=True")]
        public string VanHoaDienAnhConnectionString {
            get {
                return ((string)(this["VanHoaDienAnhConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS2005;Initial Catalog=ERP.Sale.2.9.1;Integrated Security=T" +
            "rue")]
        public string QLBH_2_8ConnectionString {
            get {
                return ((string)(this["QLBH_2_8ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS2005;Initial Catalog=ERP.Sale.2.9.1;User ID=sa")]
        public string QLBH_2_9_0_0ConnectionString {
            get {
                return ((string)(this["QLBH_2_9_0_0ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LEEXUNW8\\SQLEXPRESS;Initial Catalog=\"ERP QLBH 2.9.1.4\";Integrated Sec" +
            "urity=True")]
        public string HuynhGiaKhangConnectionString {
            get {
                return ((string)(this["HuynhGiaKhangConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LEEXUNW8\\SQLEXPRESS;Initial Catalog=HuynhGiaKhang;Integrated Security" +
            "=True")]
        public string HuynhGiaKhangConnectionString1 {
            get {
                return ((string)(this["HuynhGiaKhangConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LEEXUNW8\\SQLEXPRESS;Initial Catalog=\"ERP.QLBH 2.9.1.4\";Integrated Sec" +
            "urity=True")]
        public string ERP_QLBH_2_9_1_4ConnectionString {
            get {
                return ((string)(this["ERP_QLBH_2_9_1_4ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LEEXUNW8\\SQLEXPRESS;Initial Catalog=\"ERP.QLBH 2.9.1.4 StockAuth\";Inte" +
            "grated Security=True")]
        public string ERP_QLBH_2_9_1_4_StockAuthConnectionString {
            get {
                return ((string)(this["ERP_QLBH_2_9_1_4_StockAuthConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;Initial Catalog=QLBH.2.9.1.4;Integrated Security=True")]
        public string QLBH_2_9_1_4ConnectionString {
            get {
                return ((string)(this["QLBH_2_9_1_4ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQL2005EXPRESS;Initial Catalog=hongdanhbl;Integrated Security=True")]
        public string hongdanhblConnectionString {
            get {
                return ((string)(this["hongdanhblConnectionString"]));
            }
        }
    }
}
