//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Perfect.Inventory.Report.Report.Summary.LNG {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Summary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Summary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Perfect.Inventory.Report.Report.Summary.LNG.Summary", typeof(Summary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhóm.
        /// </summary>
        internal static string riCatalogID {
            get {
                return ResourceManager.GetString("riCatalogID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhóm.
        /// </summary>
        internal static string riCatalogName {
            get {
                return ResourceManager.GetString("riCatalogName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kế toán trưởng.
        /// </summary>
        internal static string riChief {
            get {
                return ResourceManager.GetString("riChief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị.
        /// </summary>
        internal static string riCloseAmount {
            get {
                return ResourceManager.GetString("riCloseAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng.
        /// </summary>
        internal static string riCloseQuantity {
            get {
                return ResourceManager.GetString("riCloseQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuối kỳ.
        /// </summary>
        internal static string riClosingBalance {
            get {
                return ResourceManager.GetString("riClosingBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày:.
        /// </summary>
        internal static string riDate {
            get {
                return ResourceManager.GetString("riDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày.........tháng..........năm ........
        /// </summary>
        internal static string riDateNote {
            get {
                return ResourceManager.GetString("riDateNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        internal static string riFax {
            get {
                return ResourceManager.GetString("riFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thủ trưởng đơn vị.
        /// </summary>
        internal static string riHeadOfUnit {
            get {
                return ResourceManager.GetString("riHeadOfUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập kho.
        /// </summary>
        internal static string riInward {
            get {
                return ResourceManager.GetString("riInward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị.
        /// </summary>
        internal static string riInwardAmount {
            get {
                return ResourceManager.GetString("riInwardAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng.
        /// </summary>
        internal static string riInwardQuantity {
            get {
                return ResourceManager.GetString("riInwardQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STT.
        /// </summary>
        internal static string riNo {
            get {
                return ResourceManager.GetString("riNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị.
        /// </summary>
        internal static string riOpenAmount {
            get {
                return ResourceManager.GetString("riOpenAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đầu kỳ.
        /// </summary>
        internal static string riOpeningBalance {
            get {
                return ResourceManager.GetString("riOpeningBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng.
        /// </summary>
        internal static string riOpenQuantity {
            get {
                return ResourceManager.GetString("riOpenQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất kho.
        /// </summary>
        internal static string riOutward {
            get {
                return ResourceManager.GetString("riOutward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị.
        /// </summary>
        internal static string riOutwardAmount {
            get {
                return ResourceManager.GetString("riOutwardAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng.
        /// </summary>
        internal static string riOutwardQuantity {
            get {
                return ResourceManager.GetString("riOutwardQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người lập.
        /// </summary>
        internal static string riPrepaid {
            get {
                return ResourceManager.GetString("riPrepaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã Hàng.
        /// </summary>
        internal static string riProductID {
            get {
                return ResourceManager.GetString("riProductID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hàng hóa.
        /// </summary>
        internal static string riProductName {
            get {
                return ResourceManager.GetString("riProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ký, đóng đấu, ghi rõ họ tên.
        /// </summary>
        internal static string riSign1 {
            get {
                return ResourceManager.GetString("riSign1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ký, ghi rõ họ tên.
        /// </summary>
        internal static string riSign2 {
            get {
                return ResourceManager.GetString("riSign2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ký, ghi rõ họ tên.
        /// </summary>
        internal static string riSign3 {
            get {
                return ResourceManager.GetString("riSign3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên Kho.
        /// </summary>
        internal static string riStockName {
            get {
                return ResourceManager.GetString("riStockName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cộng:.
        /// </summary>
        internal static string riSum {
            get {
                return ResourceManager.GetString("riSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ĐT.
        /// </summary>
        internal static string riTel {
            get {
                return ResourceManager.GetString("riTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THẺ KHO.
        /// </summary>
        internal static string riTitle {
            get {
                return ResourceManager.GetString("riTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng:.
        /// </summary>
        internal static string riTotal {
            get {
                return ResourceManager.GetString("riTotal", resourceCulture);
            }
        }
    }
}
